### ISSUE TITLE
Agregar Google Analytics configurable desde .env

### ISSUE THREAD

**Issue by dcatanzaro** [dcatanzaro/cafecito#11]

**Comment by matias4205** [comment]
Estoy trabajando en esto, te parece usar [esta](https://www.npmjs.com/package/react-ga) libreria?

**Comment by dcatanzaro** [comment]
> Estoy trabajando en esto, te parece usar [esta](https://www.npmjs.com/package/react-ga) libreria?

No hace falta usar una librería en estos casos, con armar un componente que tenga esto adentro ya está.

<script
            dangerouslySetInnerHTML={{
                __html: `(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
                    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
                    
                    ga('create', ${process.env.GA_ID}, 'auto');
                    ga('send', 'pageview');`
            }}
        />

**Comment by matias4205** [comment]
Ahh bueno, si es para trackear las visitas no hace falta, yo decía por si queriamos trackear algo mas especifico.
