### ISSUE TITLE
Ver como solucionar el mini switch entre light mode a dark mode cuando se entra por primera vez a la página

### ISSUE THREAD

**Issue by dcatanzaro** [dcatanzaro/cafecito#13]

**Comment by matias4205** [comment]
En teoria este problema esta resuelto. Por lo que vi lo solucionaron guardando el tema en el estado de "Home" y pasandoselo a "Header" que a su vez tambien lo guarda en su estado, forzando a hacer re-render del componente. Estoy preparando un refactor que lo hace de una manera un poco mas simple y separa la logica del tema en un hook reutilizable
