### ISSUE TITLE
'NODE_ENV' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by kaizendevar** [dcatanzaro/cafecito#2]
Martin-PC@DESKTOP-NI9N5JU MINGW64 /c/src/cafecito (master)
$ npm run dev

> cafecito@0.1.0 dev C:\src\cafecito
> NODE_ENV=production nodemon server.js

'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.

**Solution**:

In Package.json file change this line:

`"dev": "NODE_ENV=production nodemon server.js",`

For this:

`"dev": "SET NODE_ENV=development & nodemon server.js",`

**Comment by dcatanzaro** [comment]
Que raro, con el SET me tira error a mi, estás en Windows no? Creo que ese es el problema, hay que averiguar una forma que funcione en ambos SO.

**Comment by kaizendevar** [comment]
Sí, estoy en Windows.

Solución para que funcione en MacOS y Windows:

`npm install --save-dev cross-env`

Agregar cross-env al inicio:

`"dev": "cross-env NODE_ENV=development nodemon server.js",`

**Comment by dcatanzaro** [comment]
10 puntos, ahora lo agrego y subo, gracias!
