### ISSUE TITLE
Server started on port undefined | Url: undefined

### ISSUE THREAD

**Issue by kaizendevar** [dcatanzaro/cafecito#3]
I tried creating .env file with NODE_ENV=development but doesn't work.

**Solution**:

In **server.js** file replace this line (#4):

const envFile = isDev ? `.env.${process.env.NODE_ENV}` : ".env";

for this line:

`const envFile = isDev ? ".env.development" : ".env";`

**Comment by dcatanzaro** [comment]
Esto está ligado a este issue #2, sigamos en el otro.
